version: '3.8'

services:
  malcolm:
    container_name: malcolm
    build: 
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
        - ./app:/app
    networks:
      - local-network
    restart: unless-stopped 
  ftp-server:
    container_name: server
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    env_file:
      - dev.env
    ports:
      - "21:21"
      - "10000-10009"
    networks:
      - local-network
    restart: unless-stopped 
  ftp-client:
    build:
      context: ./ftp-client
      dockerfile: Dockerfile
    container_name: client
    networks:
      - local-network
    restart: unless-stopped
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - "3000:3000"
    networks:
      - local-network
    restart: unless-stopped

networks:
  local-network:
    driver: bridge